# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pfaust <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/25 21:32:27 by pfaust            #+#    #+#              #
#    Updated: 2017/07/25 21:55:10 by pfaust           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all : $(NAME)

$(NAME) :
	gcc -Wall -Wextra -Werror *.c -o $(NAME)

clean :
	rm -f *.o

fclean : clean
	rm -f $(NAME)

re : fclean all
